#!/usr/bin/env python3
import os.path
import sys
import argparse
from __init__ import VERSION, DEFAULTDEVICE
from epicmon import epicMon
from datetime import datetime

USAGE = \
"""
epicmon
"""

DESCRIPTION = \
"""
epicmon - A utility to monitor and display status of a West Mountain Radio Epic Power Gate.
"""

EPILOG = \
"""
That is all!
"""

def parseMyArgs():
    parser = argparse.ArgumentParser(\
                    description = DESCRIPTION, usage = USAGE)
    parser.add_argument('-v', '--version', 
                        action='version', 
                        version = VERSION)

    parser.add_argument('-c', '--cpuTemp',
                    default =  False,
                    action = 'store_true',
            help="""Read and display CPU temperature in celcius.""")

    parser.add_argument('-d', '--deviceName',
                                   default = DEFAULTDEVICE,
            help="""Use deviceName as serial input device.
                    default is {}""".format(DEFAULTDEVICE))

    parser.add_argument('-s', '--epicStatus',
                    default =  False,
                    action = 'store_true',
            help="""Display status in a more human readable format.""")

    parser.add_argument('-r', '--noderedStatus',
                    default =  False,
                    action = 'store_true',
            help="""Formatted status for display in Node Red.""")

    parser.add_argument('-t', '--epicMonTerm',
                    default =  None,
            help="""Display raw status N lines of output from 
                    the Epic PowerGate and quit. Entering a value
                    of 0 will cause the stream to run indefinately.
                    """)

    parser.add_argument('-V', '--epicVersion',
                    default =  False,
                    action = 'store_true',
            help="""Read and report the Epic PowerGate verison.""")

    args = parser.parse_args()
    return args

if __name__ == '__main__':
    args = parseMyArgs()
    if args.deviceName:
        pgate = epicMon(args.deviceName)
    if pgate:
        if args.cpuTemp:
            print('Host CPU Temperature: {} \'C'.format(pgate.getcpuTemp()[0]))
        elif args.epicVersion:
            for s in (pgate.getEpicVersion()):
                print(s)
        elif args.epicMonTerm:
            pgate.epicMonTerm(args.epicMonTerm)
        elif args.epicStatus:
            pgate.showStatus()
        elif args.noderedStatus:
            pgate.showNR()
